#!/usr/bin/env bash
#export SPARK_HOME="/home/roman/Downloads/spark-0.8.1-incubating"
echo "SPARK_HOME: $SPARK_HOME"
JAR=target/clj-spark-0.1.0-SNAPSHOT-standalone.jar
CLASSPATH="$JAR"
CLASSPATH="$CLASSPATH:$SPARK_HOME/examples/target/scala-2.9.3/spark-examples-assembly-0.8.1-incubating.jar"
CLASSPATH="$CLASSPATH:$SPARK_HOME/conf"
CLASSPATH="$CLASSPATH:$SPARK_HOME/assembly/target/scala-2.9.3/spark-assembly-0.8.1-incubating-hadoop1.0.4.jar"
CLASSPATH="$CLASSPATH:/etc/hadoop"
java -cp $CLASSPATH clj_spark.examples.word_count spark://bombaclaat:7077 LICENSE $JAR
